- hosts: localhost
#  vars:
#    - docker_inventory: ""
#    - docker_inventory_group: [ 'dollydk01', 'dollydk02', 'dollydk03', 'dollydk04', 'dollydk05', 'dollydk06', ]
#    - docker_groups: [ 'net-docks', ]
#    - docker_privileged: true
#    - docker_network: docknet
#    - docker_ip: "127.0.0.1"
#    - docker_use_tls: true
#    - docker_state: started
#    - docker_use_docker_connection: true
#    - docker_image_default: "tmeralus/ansible-node"
  roles:
  - role: tmeralus.docker_playground
#  tasks:
#    - import_tasks: "{{ playbook_dir }}/tasks/main.yml"
