- hosts: localhost
  vars:
    - provision_docker_inventory: ""
    - provision_docker_inventory_group: [ 'dollydk01', 'dollydk02', 'dollydk03', 'dollydk04', 'dollydk05', 'dollydk06', ]
    - provision_docker_groups: [ 'net-docks', ]
    - provision_docker_privileged: true
    - provision_docker_network: docktestnet
    - provision_docker_ip: "127.0.0.1"
    - provision_docker_use_tls: true
    - provision_docker_state: started
    - provision_docker_use_docker_connection: true
    - provision_docker_image_default: "tmeralus/ansible-node"
#  roles:
#  - role: tmeralus.docker_playground
  # for testing purposes
  tasks:
    - import_tasks: "{{ playbook_dir }}/tasks/main.yml"
