- name: Create a Docker Network
  docker_network:
    name: "{{ docker_network }}"
    ipam_config:
      - subnet: "{{ docker_subnet }}"
        gateway: "{{ docker_gateway }}"
        iprange: "{{ docker_iprange }}"

- name: Bring up inventory group of hosts
  docker_container:
    name: "{{ item }}"
    image: "{{ docker_image_default }}"
    privileged: "{{ docker_privileged }}"
    state: "{{ docker_state }}"
    tls: "{{ docker_use_tls }}"
    stop_timeout: 1
    tty: "{{ docker_use_docker_connection }}"
    exposed: "{{ docker_exposed }}"
    ports: "{{ docker_ports }}"
    network_mode: "{{ docker_network }}"
    volumes: "{{ docker_volumes }}"
    volumes_from: "{{ docker_volumes_from }}"
    restart: "{{ docker_restart|default(omit) }}"
    pull: "{{ docker_pull|default(omit) }}"
    command: "{{ docker_command|default(omit) }}"
    links: "{{ docker_links|default(omit) }}"
  with_items: "{{ docker_inventory_group }}"
