- name: Create a Docker Network
  docker_network:
    name: "{{ provision_docker_network }}"
    ipam_config:
      - subnet: '172.18.0.0/16'
        gateway: 172.18.0.1
        iprange: 172.18.0.0/26

- name: Bring up inventory group of hosts
  docker_container:
    # |default(random_hostname)
    name: "{{ item }}"
    image: "{{ provision_docker_image_default }}"
    privileged: "{{ provision_docker_privileged }}"
    state: "{{ provision_docker_state }}"
    restart: "{{ provision_docker_restart }}"
    tls: "{{ provision_docker_use_tls }}"
    stop_timeout: 1
    tty: "{{ provision_docker_use_docker_connection }}"
    exposed: "{{ provision_docker_exposed }}"
    ports: "{{ provision_docker_ports }}"
    command: "{{ provision_docker_command }}"
    env: "{{ provision_docker_env }}"
    links: "{{ provision_docker_links }}"
    network_mode: "{{ provision_docker_network }}"
    volumes: "{{ provision_docker_volumes }}"
    volumes_from: "{{ provision_docker_columes_from }}"
    pull: "{{ provision_docker_pull }}"
  with_items: "{{ provision_docker_inventory_group }}"
