- name: Bring up inventory group of hosts
  docker_container:
    # |default(random_hostname)
    name: "{{ item }}"
    image: "{{ docker_image_default }}"
    privileged: "{{ docker_privileged }}"
    state: "{{ docker_state }}"
    restart: "{{ hostvars[item].restart|default(True) }}"
    tls: "{{ docker_use_tls }}"
    stop_timeout: 1
    tty: "{{ docker_use_docker_connection }}"
    exposed: "{{ hostvars[item].expose|default(['1-65535']) }}"
    ports: "{{ hostvars[item].ports|default(omit) }}"
    command: "{{ hostvars[item].command|default(omit) }}"
    env: "{{ hostvars[item].env|default(omit) }}"
    links: "{{ hostvars[item].links|default(omit) }}"
    network_mode: "{{ hostvars[item].network_mode|default(docker_network) }}"
    volumes: "{{ docker_volumes|default(omit) }}"
    volumes_from: "{{ docker_volumes_from|default(omit) }}"
    pull: "{{ hostvars[item].pull|default(omit) }}"
  with_items: "{{ docker_inventory_group }}"
