- name: Create a Docker Network
  docker_network:
    name: "{{ provision_docker_network }}"

- name: 1 Bring up inventory group of hosts
  docker_container:
    # |default(random_hostname)
    name: "{{ item }}"
    image: "{{ provision_docker_image_default }}"
    privileged: "{{ provision_docker_privileged }}"
    state: "{{ provision_docker_state }}"
    restart: "{{ hostvars[item].restart|default(True) }}"
    tls: "{{ provision_docker_use_tls }}"
    stop_timeout: 1
    tty: "{{ provision_docker_use_docker_connection }}"
    exposed: "{{ hostvars[item].expose|default(['1-65535']) }}"
    ports: "{{ hostvars[item].ports|default(omit) }}"
    command: "{{ hostvars[item].command|default(omit) }}"
    env: "{{ hostvars[item].env|default(omit) }}"
    links: "{{ hostvars[item].links|default(omit) }}"
    network_mode: "{{ hostvars[item].network_mode|default(provision_docker_network) }}"
    volumes: "{{ provision_docker_volumes|default(omit) }}"
    volumes_from: "{{ provision_docker_volumes_from|default(omit) }}"
    pull: "{{ hostvars[item].pull|default(omit) }}"
  with_items: "{{ provision_docker_inventory_group }}"
