- name: Create a Docker Network
  docker_network:
    name: "{{ docker_network }}"
  #  connected: "{{ item }}"
  #  appends: yes
  #with_items: "{{ docker_inventory_group }}"

- name: add port 4243 to localhost
  iptables:
   chain: INPUT
   protocol: tcp
   jump: ACCEPT
   destination_port: 4243
  delegate_to: localhost
  become: true
  ignore_errors: true
