- hosts: localhost
  vars:
    inventory:
      - name: dolly01
      - name: dolly02
      - name: dolly03
      - name: dolly04
      - name: dolly05
      - name: dolly06
    provision_docker_inventory: "{{inventory}}"
    provision_docker_inventory_group: [ 'dolly01', 'dolly02', 'dolly03', 'dolly04', 'dolly05', 'dolly06', ]
    provision_docker_groups: [ 'net-docks', ]
    provision_docker_privileged: true
    provision_docker_network: null
    provision_docker_ip: "127.0.0.1"
    provision_docker_ssh_user: "ansible"
    provision_docker_ssh_pass: "docker"
    provision_docker_use_tls: true
    provision_docker_state: "started"
    provision_docker_use_docker_connection: true
  tasks:
    - name: Ensure required vars are defined
      fail: msg="provision_docker_inventory_group or provision_docker_inventory is required"
      when: "provision_docker_inventory_group is not defined and provision_docker_inventory is not defined"

    - import_tasks: setup_requirements.yml

    - import_tasks: inc_inventory_iface.yml
      when: (provision_docker_inventory_group | length) > 0

#    - import_tasks: inc_cloud_iface.yml
#      when: (provision_docker_inventory | length) > 0
