
# Install dependancies
- import_tasks: "setup_requirements.yml"
- import_tasks: "tasks/dock_network.yml"
- import_tasks: "tasks/dock_inventory.yml"
  when: (provision_docker_inventory_group | length) > 0
