---
- name: Ensure required vars are defined
  fail: msg="provision_docker_inventory_group or provision_docker_inventory is required"
  when: "provision_docker_inventory_group is not defined and provision_docker_inventory is not defined"

- name: Gather facts
  setup:

- name: Install libselinux-python package for 'copy' task
  package:
    name: libselinux-python
    state: present
  when: ansible_os_family == "RedHat"
